import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nahalil's Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full font-sans text-mycolor2">
        {children}
      </body>
    </html>
  );
}
